### ISSUE TITLE
your indexed records for Harris, L.D. and Paur, L. (1972). A quantitative food web analysis of a shortgrass community, Technical Report No. 154, Grassland Biome. (U.S. International Biological Program). 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalwebdb#1]
Hi!

Thanks for helping to make existing biotic interaction data easier to find and access!

I was just looking at your GloBI indexed record at https://www.globalbioticinteractions.org/?interactionType=eats&sourceTaxon=Lepus%20townsendii and I was wondering about ... 

https://discuss.eol.org/t/questionable-link-in-trophic-web-for-white-tailed-jackrabbit/2296

> [lumbrjak](https://discuss.eol.org/u/lumbrjak) Ryan Hill said:
>
> on the page for White-tailed jackrabbit, the common mallard (duck) is shown as prey (food source). This is incorrect.

**Comment by jhpoelen** [comment]
fyi @jhammock

**Comment by jhpoelen** [comment]
![image](https://github.com/globalbioticinteractions/globalwebdb/assets/1084872/01b9159b-a0d1-470c-ab27-921b003887eb)

for more info, see https://depot.globalbioticinteractions.org/reviews/globalbioticinteractions/globalwebdb/ .

**Comment by jhpoelen** [comment]
```
neo4j> start taxon = node:taxons('name:"Anas platyrhynchos"'), otherTaxon = node:taxons('name:"Lepus townsendii"') match taxon<-[:CLASSIFIED_AS]-specimen-->otherSpecimen-[:CLASSIFIED_AS]->otherTaxon,specimen-[:ORIGINALLY_DESCRIBED_AS]->origTaxon  return origTaxon.name,taxon.name, otherTaxon.name LIMIT 20;
+--------------------------------------------------------------------------+
| origTaxon.name               | taxon.name           | otherTaxon.name    |
+--------------------------------------------------------------------------+
| "crested wheatgrass (grass)" | "Anas platyrhynchos" | "Lepus townsendii" |
+--------------------------------------------------------------------------+

1 row available after 425 ms, consumed after another 6 ms
```

from GloBI 2023-10-26 search index, I found that for some reason "crested wheatgrass (grass)" was interpreted as  "Anas platyrhynchos".

Which was confirmed by Nomer v0.5.6 -

```
echo -e '\tcrested wheatgrass'\
 | nomer append --include-header globi\
 | mlr --itsvlite --omd cat
```

| providedExternalId | providedName | relationName | resolvedExternalId | resolvedName | resolvedAuthorship | resolvedRank | resolvedCommonNames | resolvedPath | resolvedPathIds | resolvedPathNames | resolvedPathAuthorships | resolvedExternalUrl |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  | crested wheatgrass | SAME_AS | GBIF:9761484 | Anas platyrhynchos |  | species | Anade Azulón @es \| Canard colvert @fr \| Canard colvert @fr \| Germano reale @it \| Germano reale @it \| Groenkopeend @af \| Gräsand @sv \| Gråand @da \| Gråand @da \| Kachna divoká @cs \| Mallard @en \| Mallard @en \| Mallard @en \| Mallard @en \| Mallard @en \| Mallard @en \| Mallard @en \| Mallard @en \| Mallard @en \| Mallard @en \| Mallard @en \| Mallard/American Black Duck @en \| Mallard/Mottled Duck @en \| Pato de collar @es \| Pato de collar @es \| Pato de collar @es \| Pato-real @pt \| Sinisorsa @fi \| Stackint @lb \| Stockente @de \| Stockente @de \| Stockente @de \| Stockente @de \| Stokkand @no \| Wilde Eend @nl \| Wilde Eend @nl \| Wëll Int @lb \| canard colvert @fr \| canard colvert @fr \| canard colvert @fr \| canard colvert @fr \| didžioji antis @lt \| gräsand @sv \| kachna divoká @cs \| kačica divá @sk \| krzyżówka @pl \| mallard @en \| mallard @en \| mallard @en \| meža pīle @lv \| mlakarica @sl \| pato-real @pt \| sinikael-part @et \| sinisorsa @fi \| tőkés réce @hu \| wilde eend @nl \| Ánade azulón @es \| ànec collverd @ca \| Кряква @ru \| เป็ดหัวเขียว @th \| マガモ @ja \| 綠頭鴨 @zh \| 绿头鸭 @zh \| Gråand @da \| Mallard @en \| Mallard @en \| Sinisorsa @fi \| Stockente @de \| Stokkand @nb \| Stokkönd @is \| Villdunna @fo \| Wilde eend @nl \| duoršu @se \| gräsand @sv | Animalia \| Chordata \| Aves \| Anseriformes \| Anatidae \| Anas \| Anas platyrhynchos | GBIF:1 \| GBIF:44 \| GBIF:212 \| GBIF:1108 \| GBIF:2986 \| GBIF:2498056 \| GBIF:9761484 | kingdom \| phylum \| class \| order \| family \| genus \| species |  | http://www.gbif.org/species/9761484 |
|  | crested wheatgrass | SAME_AS | http://treatment.plazi.org/id/3E646DBBCB296C3DC937CF6A20FF2EFB | http://treatment.plazi.org/id/3E646DBBCB296C3DC937CF6A20FF2EFB |  |  |  | http://treatment.plazi.org/id/3E646DBBCB296C3DC937CF6A20FF2EFB |  |  |  | http://treatment.plazi.org/id/3E646DBBCB296C3DC937CF6A20FF2EFB |
|  | crested wheatgrass | SAME_AS | http://treatment.plazi.org/id/722445E56509F69A6A32B6F576121D1E | http://treatment.plazi.org/id/722445E56509F69A6A32B6F576121D1E |  |  |  | http://treatment.plazi.org/id/722445E56509F69A6A32B6F576121D1E |  |  |  | http://treatment.plazi.org/id/722445E56509F69A6A32B6F576121D1E |
|  | crested wheatgrass | SAME_AS | INAT_TAXON:6930 | Anas platyrhynchos |  | species |  | Animalia \| Chordata \| Aves \| Anseriformes \| Anatidae \| Anas \| Anas platyrhynchos |  | kingdom \| phylum \| class \| order \| family \| genus \| species |  | https://data.nbn.org.uk/Taxa/NBNSYS0000000007 |
|  | crested wheatgrass | SAME_AS | IRMNG:10840147 | Anas platyrhynchos |  | species |  | Animalia \| Chordata \| Aves \| Anseriformes \| Anatidae \| Anas \| Anas platyrhynchos | IRMNG:11 \| IRMNG:148 \| IRMNG:1142 \| IRMNG:10908 \| IRMNG:104622 \| IRMNG:1105530 \| IRMNG:10840147 | kingdom \| phylum \| class \| order \| family \| genus \| species |  | https://data.nbn.org.uk/Taxa/NBNSYS0000000007 |
|  | crested wheatgrass | SAME_AS | ITIS:175063 | Anas platyrhynchos |  | species |  | Animalia \| Bilateria \| Deuterostomia \| Chordata \| Vertebrata \| Gnathostomata \| Tetrapoda \| Aves \| Anseriformes \| Anatidae \| Anas \| Anas platyrhynchos | ITIS:202423 \| ITIS:914154 \| ITIS:914156 \| ITIS:158852 \| ITIS:331030 \| ITIS:914179 \| ITIS:914181 \| ITIS:174371 \| ITIS:174982 \| ITIS:174983 \| ITIS:175062 \| ITIS:175063 | kingdom \| subkingdom \| infrakingdom \| phylum \| subphylum \| infraphylum \| superclass \| class \| order \| family \| genus \| species |  | http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=175063 |
|  | crested wheatgrass | SAME_AS | NCBI:4593 | Agropyron cristatum |  | species |  | root \| cellular organisms \| Eukaryota \| Viridiplantae \| Streptophyta \| Streptophytina \| Embryophyta \| Tracheophyta \| Euphyllophyta \| Spermatophyta \| Magnoliopsida \| Mesangiospermae \| Liliopsida \| Petrosaviidae \| commelinids \| Poales \| Poaceae \| BOP clade \| Pooideae \| Triticodae \| Triticeae \| Hordeinae \| Agropyron \| Agropyron cristatum | NCBI:1 \| NCBI:131567 \| NCBI:2759 \| NCBI:33090 \| NCBI:35493 \| NCBI:131221 \| NCBI:3193 \| NCBI:58023 \| NCBI:78536 \| NCBI:58024 \| NCBI:3398 \| NCBI:1437183 \| NCBI:4447 \| NCBI:1437197 \| NCBI:4734 \| NCBI:38820 \| NCBI:4479 \| NCBI:359160 \| NCBI:147368 \| NCBI:1648038 \| NCBI:147389 \| NCBI:1648017 \| NCBI:4592 \| NCBI:4593 | null \| null \| superkingdom \| kingdom \| phylum \| subphylum \| null \| null \| null \| null \| class \| null \| null \| subclass \| null \| order \| family \| null \| subfamily \| null \| tribe \| subtribe \| genus \| species |  | https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=4593 |
|  | crested wheatgrass | SAME_AS | WORMS:148791 | Anas platyrhynchos |  | species | ánade azulón @es \| canard colvert @fr \| didžioji antis @lt \| germano reale @it \| gråand @da \| gräsand @sv \| hwyaden wyllt @ wel  \| krzyżówka @pl \| kuqëla @ alb  \| mallard @en \| mallard @gd \| mlakarica @sl \| raţa mare @ro \| raţă mare @ro \| rosa e egër @ alb  \| rosa e vendit @ alb  \| rosa jeshile @ alb  \| Stockente @de \| stokkand @no \| stokkand @nb \| stokkand @nn \| wilde eend @ dut  \| yeşilbaş @tr \| Πρασινοκέφαλη πάπια @ gre  \| или крыженъ @ru \| или кряковная утка @ru \| Крижень @uk \| кряква @ru \| ברכייה @he \| マガモ @ja | Biota \| Animalia \| Chordata \| Vertebrata \| Gnathostomata \| Tetrapoda \| Aves \| Anseriformes \| Anatidae \| Anas \| Anas platyrhynchos | WORMS:1 \| WORMS:2 \| WORMS:1821 \| WORMS:146419 \| WORMS:1828 \| WORMS:1831 \| WORMS:1836 \| WORMS:2681 \| WORMS:136973 \| WORMS:148788 \| WORMS:148791 | superdomain \| kingdom \| phylum \| subphylum \| superclass \| superclass \| class \| order \| family \| genus \| species |  | https://www.marinespecies.org/aphia.php?p=taxdetails&id=148791 |

**Comment by jhpoelen** [comment]
The suspicious mappings can be found in 

Poelen, J. H. (2023). Global Biotic Interactions: Taxon Graph [Data set]. Zenodo. https://doi.org/10.5281/zenodo.10037600

taxonMap.tsv.gz on lines L942719-L942724,L942726 , or

```
preston cat --remote https://zenodo.org 'line:gz:hash://md5/154da7e73facf3a563f0c846a8c73963!/L942719-L942724,L942726'
 ```

rendered as markdown table via 

```
preston cat\
 --remote https://zenodo.org\
 'line:gz:hash://md5/154da7e73facf3a563f0c846a8c73963!/L1,L942719-L942724,L942726'\
 | mlr --itsvlite --omd cat
```

| providedTaxonId | providedTaxonName | resolvedTaxonId | resolvedTaxonName |
| --- | --- | --- | --- |
|  | crested wheatgrass | GBIF:9761484 | Anas platyrhynchos |
|  | crested wheatgrass | http://treatment.plazi.org/id/3E646DBBCB296C3DC937CF6A20FF2EFB | http://treatment.plazi.org/id/3E646DBBCB296C3DC937CF6A20FF2EFB |
|  | crested wheatgrass | http://treatment.plazi.org/id/722445E56509F69A6A32B6F576121D1E | http://treatment.plazi.org/id/722445E56509F69A6A32B6F576121D1E |
|  | crested wheatgrass | INAT_TAXON:6930 | Anas platyrhynchos |
|  | crested wheatgrass | IRMNG:10840147 | Anas platyrhynchos |
|  | crested wheatgrass | ITIS:175063 | Anas platyrhynchos |
|  | crested wheatgrass | WORMS:148791 | Anas platyrhynchos |

**Comment by jhpoelen** [comment]
See also 

https://linker.bio/line:gz:hash://md5/154da7e73facf3a563f0c846a8c73963!/L1,L942719-L942724,L942726


![image](https://github.com/globalbioticinteractions/globalwebdb/assets/1084872/e9668a79-d8fb-436e-82f8-20139fb641dd)

**Comment by jhammock** [comment]
Intriguing! I didn't realized you had mappings from vernacular names. The behavior sure is consistent. I suppose somewhere it was mapped to the canonical.

**Comment by jhpoelen** [comment]
@jhammock yeah, there's some leftovers from the days that mapping vernacular names was all the rage ; )

**Comment by jhpoelen** [comment]
Rather than removing the historic mappings, I'm pruning when needed. 

Naturally, all these mappings can be removed. 

In fact, the GloBI Taxon Graph was introduced about a decade ago as an optimization to avoid Web API delays/ outages. 

Now that Nomer has support for fast taxon name alignment via many taxonomic resources, perhaps we should consider retiring the GloBI Taxon Graph. 

Curious to hear your thoughts on that.

**Comment by jhammock** [comment]
Good question! I can't say that this case constitutes a reason. I've never seen anything like it before. @KatjaSchulz would have a more informed opinion...

**Comment by jhpoelen** [comment]
One option would be to separate the common name mappings to a separate mapping resource. This way, there's more of an explicit separation of concerns, and . . . it'd be easier to prune later. 

and, I am curious to hear what @KatjaSchulz has to say.

**Comment by KatjaSchulz** [comment]
I'm not sure I comprehend the entire scope of this issue, but in general, mapping via vernacular names is incredibly dangerous. I would advise against it. If a dataset can't provide scientific names, it probably has a whole host of other data quality issues.

**Comment by jhpoelen** [comment]
@KatjaSchulz thanks for taking the time to share your ideas on common names. While pondering your comments, I've prepared a fix for the specific suspicious name mapping reported. 

Now, with v0.22 of Nomer Corpus of Taxonomic resources, 

> Poelen, J. H. (ed . ) . (2023). Nomer Corpus of Taxonomic Resources hash://sha256/5d641367b570f7b3f3c3be4f778f9685f0f050a99f86d8b56475491a4810fc46 hash://md5/4940fcbc59d39aa1e0e3632984665c26 (0.22) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.10045382

```
echo -e '\tcrested wheatgrass'\
 | nomer append\
 --include-header\
 globi\
 | mlr --itsvlite --omd cat
```

produced: 

| providedExternalId | providedName | relationName | resolvedExternalId | resolvedName | resolvedAuthorship | resolvedRank | resolvedCommonNames | resolvedPath | resolvedPathIds | resolvedPathNames | resolvedPathAuthorships | resolvedExternalUrl |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  | crested wheatgrass | SAME_AS | NCBI:4593 | Agropyron cristatum |  | species |  | root \| cellular organisms \| Eukaryota \| Viridiplantae \| Streptophyta \| Streptophytina \| Embryophyta \| Tracheophyta \| Euphyllophyta \| Spermatophyta \| Magnoliopsida \| Mesangiospermae \| Liliopsida \| Petrosaviidae \| commelinids \| Poales \| Poaceae \| BOP clade \| Pooideae \| Triticodae \| Triticeae \| Hordeinae \| Agropyron \| Agropyron cristatum | NCBI:1 \| NCBI:131567 \| NCBI:2759 \| NCBI:33090 \| NCBI:35493 \| NCBI:131221 \| NCBI:3193 \| NCBI:58023 \| NCBI:78536 \| NCBI:58024 \| NCBI:3398 \| NCBI:1437183 \| NCBI:4447 \| NCBI:1437197 \| NCBI:4734 \| NCBI:38820 \| NCBI:4479 \| NCBI:359160 \| NCBI:147368 \| NCBI:1648038 \| NCBI:147389 \| NCBI:1648017 \| NCBI:4592 \| NCBI:4593 | null \| null \| superkingdom \| kingdom \| phylum \| subphylum \| null \| null \| null \| null \| class \| null \| null \| subclass \| null \| order \| family \| null \| subfamily \| null \| tribe \| subtribe \| genus \| species |  | https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=4593 |

Note that the previously recorded crested wheatgrass -> mallard (_Anas platyrhynchos_) mappings are no longer present.

**Comment by jhpoelen** [comment]
Changes associated with updated nomer corpus v0.22 to remove the suspicious translation:

 crested wheatgrass -> mallard (Anas platyrhynchos) 

appear to have propagated to the search index at https://globalbioticinteractions.org .

Now, results for White-tailed jackrabbit (_Lepus townsendii_)  diets https://www.globalbioticinteractions.org/?interactionType=eats&sourceTaxon=Lepus%20townsendii includes -

1. a refutation that white-tailed jackrabbit eat ducks. (see attached image) 
![Screenshot from 2023-11-03 10-27-35](https://github.com/globalbioticinteractions/globalwebdb/assets/1084872/51fb0d37-6992-426f-b686-1fe9191b4ff2)

2. no claims that white-tailed jackrabbit eat ducks. However, a claim that white-tailed jackrabbit eats crested wheatgrass is present (see attached screenshot). 
![image](https://github.com/globalbioticinteractions/globalwebdb/assets/1084872/b0c53716-ee39-4c27-9bd5-10ac719b00c6)
 

Closing issue.
